with open('AVEOL.js', 'r', encoding='utf-8') as f:
    content = f.read()

# Remove the old corrupted SERVICE MODALS block
cut_marker = '// ══════════════════════════════════════════════\r\n//  SERVICE MODALS'
if cut_marker in content:
    content = content[:content.index(cut_marker)]
else:
    cut_marker2 = '// ══════════════════════════════════════════════\n//  SERVICE MODALS'
    if cut_marker2 in content:
        content = content[:content.index(cut_marker2)]

modal_js = (
    "\n// ══════════════════════════════════════════════\n"
    "//  SERVICE MODALS\n"
    "// ══════════════════════════════════════════════\n"
    "document.addEventListener('DOMContentLoaded', function () {\n"
    "  var overlay = document.getElementById('modalOverlay');\n"
    "  var modalInner = document.getElementById('modalInner');\n"
    "  var modalClose = document.getElementById('modalClose');\n"
    "  if (!overlay) return;\n\n"
    "  var modals = {\n"
    "    'modal-agents': {\n"
    "      tag: '// AI Agent Deployment',\n"
    "      title: 'Custom AI Agent Deployment',\n"
    "      desc: 'We design, train, and deploy fully custom AI agents that autonomously execute your most time-consuming business tasks 24/7, without human oversight.',\n"
    "      features: ['End-to-end custom agent architecture tailored to your workflow','Deployed directly into your existing tools (Slack, CRM, email)','Trained on your business data, SOPs, and brand voice','Continuous learning — improves with every interaction','Full handover with documentation and training'],\n"
    "      roi: '⚡ Clients typically reclaim 20-30 hours per week within the first month.',\n"
    "      cta: 'See Our AI Agent Catalog', link: 'ai-agents.html'\n"
    "    },\n"
    "    'modal-outreach': {\n"
    "      tag: '// Outreach & Lead Gen',\n"
    "      title: 'AI-Powered Outreach & Lead Generation',\n"
    "      desc: 'Stop manually prospecting. Our outreach agents identify your ideal clients, craft hyper-personalized messages, follow up automatically, and book qualified meetings on your calendar.',\n"
    "      features: ['Automated prospect research from LinkedIn, web, and CRMs','Personalized cold email and DM sequences generated by AI','Smart follow-up timing based on engagement signals','Direct calendar integration for frictionless booking','Full analytics: open rates, reply rates, and meetings booked'],\n"
    "      roi: '📈 Average of 3x more meetings booked with zero extra headcount.',\n"
    "      cta: 'Build My Outreach Agent', link: 'contact.html'\n"
    "    },\n"
    "    'modal-workflow': {\n"
    "      tag: '// Workflow Automation',\n"
    "      title: 'End-to-End Workflow Automation',\n"
    "      desc: 'We map your entire operational workflow and replace every manual step with an intelligent, automated pipeline.',\n"
    "      features: ['Full workflow audit to identify every manual bottleneck','Connect any tool: HubSpot, Notion, Zapier, Google Workspace','Automated data entry, file routing, and status updates','Real-time notifications and exception handling','One-time build, runs forever with minimal maintenance'],\n"
    "      roi: '⏱ Most clients save 20+ hours per week within 2 weeks of deployment.',\n"
    "      cta: 'Automate My Workflow', link: 'contact.html'\n"
    "    },\n"
    "    'modal-multi': {\n"
    "      tag: '// Multi-Agent Orchestration',\n"
    "      title: 'Multi-Agent Orchestration Systems',\n"
    "      desc: 'We deploy a coordinated team of specialized agents that communicate, delegate tasks, and solve complex business problems as one unified intelligence layer.',\n"
    "      features: ['Architect and deploy a network of specialized sub-agents','Central orchestrator routes tasks to the right agent automatically','Parallel processing — multiple workflows run simultaneously','Ideal for agencies, large ops teams, and complex pipelines','Built-in failover and error-recovery logic'],\n"
    "      roi: '🔗 Enables total operational synchronization across departments.',\n"
    "      cta: 'Request a Custom Build', link: 'contact.html'\n"
    "    },\n"
    "    'modal-dash': {\n"
    "      tag: '// Intelligence Dashboards',\n"
    "      title: 'AI Performance & Intelligence Dashboards',\n"
    "      desc: 'Every AI system we build comes with a real-time dashboard giving you complete visibility into what your agents are doing and what they have saved you.',\n"
    "      features: ['Live view: tasks completed, time saved, cost per action','ROI tracker — see the exact monetary value of your agents','Alert system for errors, anomalies, or performance drops','Exportable weekly reports for stakeholders','Custom KPIs based on your business goals'],\n"
    "      roi: '📊 100% visibility into your AI investment at all times.',\n"
    "      cta: 'Get My Intelligence Dashboard', link: 'contact.html'\n"
    "    },\n"
    "    'modal-integration': {\n"
    "      tag: '// System Integration',\n"
    "      title: 'Full Business System Integration',\n"
    "      desc: 'We plug your entire tech stack together into one seamless, automated ecosystem — no more switching between tabs or copying data manually.',\n"
    "      features: ['Integrates with 50+ tools: HubSpot, Salesforce, Notion, Slack, Gmail','Bi-directional data sync across all platforms','Webhook and API-based connections for real-time data flow','Custom middleware built for tools with no native integration','One unified data layer — no more siloed information'],\n"
    "      roi: '🔌 Eliminates tool-switching, data duplication, and manual syncing.',\n"
    "      cta: 'Connect My Tech Stack', link: 'contact.html'\n"
    "    }\n"
    "  };\n\n"
    "  function openModal(id) {\n"
    "    var m = modals[id];\n"
    "    if (!m) return;\n"
    "    var featureHTML = m.features.map(function(f){ return '<li>' + f + '</li>'; }).join('');\n"
    "    modalInner.innerHTML = '<div class=\"modal-tag\">' + m.tag + '</div>'\n"
    "      + '<h2 class=\"modal-title\">' + m.title + '</h2>'\n"
    "      + '<p class=\"modal-desc\">' + m.desc + '</p>'\n"
    "      + '<div class=\"modal-divider\"></div>'\n"
    "      + '<div class=\"modal-section-label\">What is included</div>'\n"
    "      + '<ul class=\"modal-features\">' + featureHTML + '</ul>'\n"
    "      + '<div class=\"modal-roi-strip\">' + m.roi + '</div>'\n"
    "      + '<a href=\"' + m.link + '\" class=\"modal-cta\">' + m.cta + ' &rarr;</a>';\n"
    "    overlay.classList.add('active');\n"
    "    document.body.style.overflow = 'hidden';\n"
    "  }\n\n"
    "  function closeModal() {\n"
    "    overlay.classList.remove('active');\n"
    "    document.body.style.overflow = '';\n"
    "  }\n\n"
    "  document.querySelectorAll('[data-modal]').forEach(function(card) {\n"
    "    card.addEventListener('click', function() { openModal(card.getAttribute('data-modal')); });\n"
    "  });\n\n"
    "  modalClose.addEventListener('click', closeModal);\n"
    "  overlay.addEventListener('click', function(e) { if (e.target === overlay) closeModal(); });\n"
    "  document.addEventListener('keydown', function(e) { if (e.key === 'Escape') closeModal(); });\n"
    "});\n"
)

content = content + modal_js

with open('AVEOL.js', 'w', encoding='utf-8') as f:
    f.write(content)

print('Modal JS written successfully.')
